### ISSUE TITLE
Error: Cannot find module 'cheerio'

### ISSUE THREAD

**Issue by julienbechade** [typhonjs-node-esdoc/esdoc-plugin-dependency-graphs#1]
Hi,

For reference, this is _nearly_ the same [issue](https://github.com/typhonjs-node-esdoc/esdoc-plugin-enhanced-navigation/issues/1#issuecomment-221848992) that has been reported in [`esdoc-plugin-enhanced-navigation/`](https://github.com/typhonjs-node-esdoc/esdoc-plugin-enhanced-navigation/issues/1#issuecomment-221848992).

I'm having a related problem with `0.0.3` version of this plugin.

``` bash
/node_modules/esdoc/out/src/Plugin/Plugin.js:94
            throw _iteratorError;
            ^

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/node_modules/esdoc-plugin-dependency-graphs/dist/plugin.js:20:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

When looking at the `node_modules/` folder, only 2 dependencies are installed: `underscore`, `fs-extra`.
I don't know how you reference external packages but their no trace of required modules used in `dist/plugins.js` in `package.json`.

Cheers.

**Comment by typhonrt** [comment]
@julienbechade Do you have esdoc installed? cheerio is a dependency of esdoc and I should probably add esdoc in peerDependencies for esdoc-plugin-enhanced-navigation

Also what version of Node are you using? I've designed things for NPM 3+ / Node 5+ which has a flat package structure. This doesn't immediately look like the problem though.

**Comment by julienbechade** [comment]
See [answer](https://github.com/typhonjs-node-esdoc/esdoc-plugin-enhanced-navigation/issues/1#issuecomment-221861654) in `esdoc-plugin-enhanced-navigation`.

**Comment by julienbechade** [comment]
I actually saw the warning for `{ npm: '>=3.x' }` but read it as Node… Typical.
